In [15]:
from cProfile import label
from heapq import nlargest
from os import name

#dataframe的创建方式
import pandas as pd
import numpy as np
from jedi.plugins import flask
from jupyter_client.localinterfaces import is_local_ip
from numpy.ma.extras import column_stack
from pandas.conftest import ascending
from pandas.core.algorithms import value_counts_arraylike
from pip._internal.commands import index

from 生成器 import df

#通过series直接创建
s1 = pd.Series([1,2,3,4,5,6])
s2 = pd.Series([11,12,13,14,15,16])
df = pd.DataFrame({"第一列":s1,"第二列":s2})
type(df["第一列"])
#通过字典创建
df = pd.DataFrame({
    "id":[1,2,3,4,5,6],
    "name":["A","B","C","D","E","F"],
},index=[1,2,3,4,5,6],columns=["id","name"]#INDEX指代行索引，column指代列索引
)
df

   id name
1   1    A
2   2    B
3   3    C
4   4    D
5   5    E
6   6    F

In [18]:
#dataframe的属性
print('行索引:')
print(df.index)
print('列标签')
print(df.columns)
print('值')
print(df.values)

行索引:
Index([1, 2, 3, 4, 5, 6], dtype='int64')
列标签
Index(['id', 'name'], dtype='str')
值
[[1 'A']
 [2 'B']
 [3 'C']
 [4 'D']
 [5 'E']
 [6 'F']]

In [24]:
print('维度:',df.ndim)
print('数据类型:')
print(df.dtypes)
print('形状：',df.shape)
print('元素个数',df.size)

维度: 2
数据类型:
id      int64
name      str
dtype: object
形状： (6, 2)
元素个数 12

In [29]:
#行列转置
print(df.T.index)

Index(['id', 'name'], dtype='str')

In [45]:
#获取某行元素 loc lioc at iat
df
print(df.loc[4])#隐式索引
print(df.iloc[3])#显示索引
#获取某列数据
print(df.loc[:,'name'])
print(df.iloc[:,0])
#获取单个数据
print(df.at[1,'name'])
print(df.iat[2,1])
print(df.iloc[2,1])

id      4
name    D
Name: 4, dtype: object
id      4
name    D
Name: 4, dtype: object
1    A
2    B
3    C
4    D
5    E
6    F
Name: name, dtype: str
1    1
2    2
3    3
4    4
5    5
6    6
Name: id, dtype: int64
A
C
C

In [51]:
#获取单列数据
print(df['name'])
print(df.name)
print(type(df[['name']]))

1    A
2    B
3    C
4    D
5    E
6    F
Name: name, dtype: str
1    A
2    B
3    C
4    D
5    E
6    F
Name: name, dtype: str
<class 'pandas.DataFrame'>

In [55]:
#获取多列数据
print(df[['id','name']])

   id name
1   1    A
2   2    B
3   3    C
4   4    D
5   5    E
6   6    F

In [59]:
#查看部分数据
print(df.head(2))
print(df.tail(2))

   id name
1   1    A
2   2    B
   id name
5   5    E
6   6    F

In [66]:
#使用布尔索引筛选数据
df[(df.id>1) & (df.id<10)]

   id name
2   2    B
3   3    C
4   4    D
5   5    E
6   6    F

In [70]:
#随机抽样
df.sample(3)

   id name
2   2    B
6   6    F
5   5    E

In [74]:
print(df.head())
print(df.isin(['A',1]))#查看元素是否包含在参数集合中

   id name
1   1    A
2   2    B
3   3    C
4   4    D
5   5    E
      id   name
1   True   True
2  False  False
3  False  False
4  False  False
5  False  False
6  False  False

In [76]:
print(df.isna())#查看元素是否是缺失值

      id   name
1  False  False
2  False  False
3  False  False
4  False  False
5  False  False
6  False  False

In [89]:
print(df['id'].sum())
print(df.id.idxmax())
print(df.id.mean())
print(df.id.median())
print(df.id.mode())
print(df.id.std())#标准差
print(df.id.var())#方差
print(df.id.quantile(0.25))

21
6
3.5
3.5
0    1
1    2
2    3
3    4
4    5
5    6
Name: id, dtype: int64
1.8708286933869707
3.5
2.25

In [91]:
print(df.describe())

             id
count  6.000000
mean   3.500000
std    1.870829
min    1.000000
25%    2.250000
50%    3.500000
75%    4.750000
max    6.000000

In [93]:
print(df.count())#每一列非缺失值个数

id      6
name    6
dtype: int64

In [95]:
print(df.value_counts())

id  name
1   A       1
2   B       1
3   C       1
4   D       1
5   E       1
6   F       1
Name: count, dtype: int64

In [99]:
print(df.drop_duplicates())
print(df.duplicated(subset='id', keep='last'))#查看是否重复，keep='last' 是 pandas 去重相关方法的一个参数，用来控制重复数据时保留哪一行

   id name
1   1    A
2   2    B
3   3    C
4   4    D
5   5    E
6   6    F
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [101]:
df.sample(2)

   id name
5   5    E
6   6    F

In [103]:
print(df.replace(2,4))

   id name
1   1    A
2   4    B
3   3    C
4   4    D
5   5    E
6   6    F

In [106]:
df.cumsum()#累加和

   id    name
1   1       A
2   3      AB
3   6     ABC
4  10    ABCD
5  15   ABCDE
6  21  ABCDEF

案例1：学生成绩分析

场景：某班级的学生成绩数据如下，请完成以下任务：
1. 计算每位学生的总分和平均分。
2. 找出数学成绩高于90分或英语成绩高于85分的学生。
3. 按总分从高到低排序，并输出前3名学生。

import pandas as pd
data = {
    '姓名': ['张三', '李四', '王五', '赵六', '钱七'],
    '数学': [85, 92, 78, 88, 95],
    '英语': [90, 88, 85, 92, 80],
    '物理': [75, 80, 88, 85, 90]
}

In [137]:
data = {
    '姓名': ['张三', '李四', '王五', '赵六', '钱七'],
    '数学': [85, 92, 78, 88, 95],
    '英语': [90, 88, 85, 92, 80],
    '物理': [75, 80, 88, 85, 90]
}
scores = pd.DataFrame(data)
#计算每位学生的总分和平均分。
scores['总分'] = scores[['数学','英语','物理']].sum(axis=1)
#在 pandas 里，当你写 df['新列名'] = 某个数据 时：如果 '总分' 这个列不存在，pandas 就会自动给 DataFrame 新增一列，列名就是 '总分'右边计算出的总分 Series，会按索引顺序一一对应地填充到新列里
scores['平均分'] = scores['总分']/3
scores['平均分2'] = scores[['数学','英语','物理']].mean(axis=1)
scores

   姓名  数学  英语  物理   总分        平均分       平均分2
0  张三  85  90  75  250  83.333333  83.333333
1  李四  92  88  80  260  86.666667  86.666667
2  王五  78  85  88  251  83.666667  83.666667
3  赵六  88  92  85  265  88.333333  88.333333
4  钱七  95  80  90  265  88.333333  88.333333

In [148]:
#2. 找出数学成绩高于90分或英语成绩高于85分的学生。
scores[(scores['数学']>90) | (scores['英语']>85)]
#3.按总分从高到低排序，并输出前3名学生。
r1 = scores.sort_values('总分', ascending=False).head(3)
r2 = scores.nlargest(3,columns=['总分'])
print(r1)
print(r2)

   姓名  数学  英语  物理   总分        平均分       平均分2
4  钱七  95  80  90  265  88.333333  88.333333
3  赵六  88  92  85  265  88.333333  88.333333
1  李四  92  88  80  260  86.666667  86.666667
   姓名  数学  英语  物理   总分        平均分       平均分2
3  赵六  88  92  85  265  88.333333  88.333333
4  钱七  95  80  90  265  88.333333  88.333333
1  李四  92  88  80  260  86.666667  86.666667

1. 计算每位用户的总消费金额（消费金额 = 商品单价 × 购买数量）
2. 找出消费金额最高的用户，并输出其所有信息
3. 计算所有用户的平均消费金额（保留2位小数）
4. 统计电子产品的总购买数量

import pandas as pd

data = {
    '用户ID': [101, 102, 103, 104, 105],
    '用户名': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    '商品类别': ['电子产品', '服饰', '电子产品', '家居', '服饰'],
    '商品单价': [1200, 300, 800, 150, 200],
    '购买数量': [1, 3, 2, 5, 4]
}

In [162]:
data = {
    '用户ID': [101, 102, 103, 104, 105],
    '用户名': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    '商品类别': ['电子产品', '服饰', '电子产品', '家居', '服饰'],
    '商品单价': [1200, 300, 800, 150, 200],
    '购买数量': [1, 3, 2, 5, 4]
}
df = pd.DataFrame(data)
df['总消费金额'] = df['商品单价']*df['购买数量']
df.nlargest(1,columns=['总消费金额'])
df['总消费金额'].mean()
df[df['商品类别']=='电子产品']['购买数量'].sum()

np.int64(3)

In [164]:
#数据分箱 pd.cut(x,bins,labels)
df = pd.read_csv('data/employees.csv')
df.head(10)

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,IT_PROG,4800.0,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,IT_PROG,4800.0,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,IT_PROG,4200.0,NaN,103.0,60.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,FI_MGR,12000.0,NaN,101.0,100.0
9,109,Daniel,Faviet,DFAVIET,515.124.4169,FI_ACCOUNT,9000.0,NaN,108.0,100.0

In [185]:
df1 = df.head(10)[['employee_id','salary']]
df1
pd.cut(df1['salary'],bins=2)#bins=n,分成了n段区间，起始值、结束值是所有数据的最小值和最大值
#4180-14100-24000
pd.cut(df1['salary'],bins=2).value_counts()
pd.cut(df1['salary'],bins=[0,10000,20000,30000])#bin=list,分区间
pd.cut(df1['salary'],bins=[0,10000,20000,30000]).value_counts()
df1['收入范围'] = pd.cut(df1['salary'],bins=[0,10000,20000,30000],labels=['低','中','高'])
pd.qcut(df1['salary'],3).value_counts()

salary
(4199.999, 6000.0]    4
(6000.0, 12000.0]     3
(12000.0, 24000.0]    3
Name: count, dtype: int64

In [197]:
#睡眠数据
df = pd.read_csv('data/sleep.csv')
df2 = df.head(10)[['person_id','sleep_quality']]
df2
df['睡眠质量'] = pd.cut(df2['sleep_quality'],bins=3,labels=['差','中等','优秀'])
df['睡眠质量'].value_counts()
df.head(10)
df['gender'] = df['gender'].astype('category')
df['gender'].value_counts()
#字符串-》类别-》统计
#数值--》分箱
print(df['gender'].dtype)
print(df['睡眠质量'].dtype)

category
category

In [207]:
#df.rename() df.set_index() df.reset_index()
df = pd.DataFrame({
    'name':['jack','alice','tom','bob'],
    'age':[20,30,40,50],
    'gender':['female','male','male','female']
})
df.set_index("name",inplace=True)#想把那一列变成索引
df
df.reset_index(inplace=True)#是否对当前df生效
df.rename(columns={"age":"年龄"},index={0:4})

    name  年龄  gender
4   jack  20  female
1  alice  30    male
2    tom  40    male
3    bob  50  female

In [212]:
df.index=[1,2,3,4]
df.columns=["姓名",'年龄',"性别"]
df

      姓名  年龄      性别
1   jack  20  female
2  alice  30    male
3    tom  40    male
4    bob  50  female

In [ ]:
#